Repository this8/password-generators, pull requests merged in 2022-10, with the labels that each got.

#3 completed code for password generator in python
  password_generator.py
Labels: hacktoberfest

#5 completed code for readable password generator in python
  password_generator.py
Labels: hacktoberfest

#8 completed code for password generator in go
  password_generator.go
  readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#10 password generator in C
  password_generator.c
Labels: hacktoberfest, hacktoberfest-accepted

#11 better
  password_generator.go
Labels: hacktoberfest-accepted

#9 Implement password generator in Bash
  password_generator.sh
Labels: hacktoberfest-accepted

#14 Create testing
  testing
Labels: hacktoberfest-accepted

#15 Create sec
  sec
Labels: hacktoberfest-accepted

#16 Create scilab code
  scilab code
Labels: hacktoberfest-accepted

#17 Create fourth
  fourth
Labels: hacktoberfest-accepted

#6 Create password_generator.java
  password_generator.java
Labels: hacktoberfest-accepted

#19 Rename testing to password_generator in laravel
  password_generator in laravel
Labels: hacktoberfest-accepted

#20 Created password generator in javascript
  password_generators.js
Labels: hacktoberfest-accepted

#21 Create home page
  img/icons8-digital-buddies-96.png
  index.html
Labels: hacktoberfest-accepted

#22 Home page css
  index.html
Labels: hacktoberfest-accepted

#24 password generator in Swift - Basic structure
  main.swift
Labels: hacktoberfest-accepted

#26 create functions for password generators
  main.swift
Labels: hacktoberfest-accepted

#27 random password generator function body
  main.swift
Labels: hacktoberfest-accepted

#28 generating password using javascript
  .vscode/settings.json
  password using js/index.css
  password using js/index.html
Labels: hacktoberfest-accepted

#32 first committ - hacktoberfest
  passgen_js.html
Labels: hacktoberfest-accepted

#33 second commit-hacktoberfest
  passgen_js.html
Labels: hacktoberfest-accepted

#34 third commit- hacktoberfest
  passgen_js.html
Labels: hacktoberfest-accepted

#35 fifth commit - hacktoberfest
  passgen_js.html
Labels: hacktoberfest-accepted

#36 Updated C code
  password_generator.c
  password_generator.php
Labels: hacktoberfest-accepted

#37 Modified password_generator.php
  password_generator.php
Labels: hacktoberfest-accepted

#38 Modified password_generator.c
  password_generator.c
Labels: hacktoberfest-accepted
